<h1>Créer un nouvel utilisateur</h1>
<form action="index.php?route=create-user" method="POST">
    <fieldset>
        <label for="firstName">Prénom</label>
        <input type="text" name="firstName" id="firstName"/>
    </fieldset>
    <fieldset>
        <label for="lastName">Nom</label>
        <input type="text" name="lastName" id="lastName"/>
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="text" name="email" id="email"/>
    </fieldset>
    <input type="submit" name="submit-create" id="submit-create" value="Submit"/>
</form>