<h1>Modifier un utilisateur</h1>
<form action="index.php?route=edit-user" method="POST">
    <fieldset>
        <label for="userId">Utilisateur à modifier</label>
        <select name="userId" id="userId">
            <?php
            foreach($data as $user)
            {
                echo "<option value='".$user['id']."'>".$user['first_name']." ".$user['last_name']."</option>";
            }
            ?>
        </select>
    </fieldset>
    <fieldset>
        <label for="firstName">Prénom</label>
        <input type="text" name="firstName" id="firstName"/>
    </fieldset>
    <fieldset>
        <label for="lastName">Nom</label>
        <input type="text" name="lastName" id="lastName"/>
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="text" name="email" id="email"/>
    </fieldset>
    <input type="submit" name="submit-edit" id="submit-edit" value="Modifier"/>
</form>